feat: adds the pitr samples
GoogleCloudPlatform/ruby-docs-samples pull request #734
Opened 2021-02-02 05:53 UTC by thiagotnunes

Adds samples for the PITR feature.

2021-02-02 05:54 UTC, thiagotnunes commented
This can only be merged after the https://github.com/googleapis/google-cloud-ruby/pull/8169 is merged and released.

2021-02-03 01:28 UTC, skuruppu approved these changes

2021-02-03 03:09 UTC, jiren requested changes

2021-02-03 03:33 UTC, thiagotnunes commented on spanner/spanner_samples.rb
> +  job = database.create_backup backup_id, expire_time, version_time
Thanks @jiren, fixed it.

2021-02-03 03:42 UTC, jiren approved these changes

2021-02-23 01:46 UTC, merged