feat(spanner): [DO NOT MERGE]  add custom replication topology samples
GoogleCloudPlatform/ruby-docs-samples pull request #960
Opened 2022-04-07 12:17 UTC by rahul2393

## Description
Added samples for supporting customer managed instance configurations

## Checklist
- [ ] **Tests** pass
- [ ] **Lint** pass: `bundle exec rubocop`
- [ ] Please **merge** this PR for me once it is approved.

2022-04-20 06:27 UTC, bajajneha27 commented on spanner/spanner_custom_instance_config.rb
> +    # TODO: remove endpoint before GA
Are we planning to raise another PR before GA?

2022-04-20 06:27 UTC, bajajneha27 commented on spanner/spanner_custom_instance_config.rb
> +  labels_map = Google::Protobuf::Map.new :string, :string
Does this have to be a `Protobuf Map` or can it be a normal hash?

2022-04-20 06:45 UTC, SandeepTuniki requested changes

2022-04-20 06:47 UTC, SandeepTuniki commented on spanner/spanner_custom_instance_config.rb
> +def update_instance_config project_id:, instance_config_id:
Something like #956 should do.

2022-08-26 14:55 UTC, bajajneha27 commented
Hi @rahul2393 
Do we still want to continue working on this?

2022-08-27 06:46 UTC, rahul2393 commented
@bajajneha27 you can close this PR, once the protos are available I will rebase and create a new PR and link this one for reference.

2022-08-27 06:46 UTC, closed without merging